parameters:
  name: 'SeleniumTestability'
  vmImage: ''
  robotPrefix: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: ${{ parameters.timeout }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python36:
        os_name:  ${{ parameters.name }}
        coverage:  ${{ parameters.coverage}}
        python_version: '3.6'
        outputdir: testresults
      Python37:
        os_name:  ${{ parameters.name }}
        coverage:  ${{ parameters.coverage}}
        python_version: '3.7'
        outputdir: testresults
    maxParallel: 6

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '11.2.0'
  - task: UsePythonVersion@0
    displayName: 'Python for test execution'
    inputs:
      versionSpec: $(python_version)
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements-dev.txt
    displayName: 'Install requirements'

  - bash: |
      inv webdrivers
    displayName: Install webdriver

  - bash: |
      brew update
      brew tap caskroom/cask
      brew cask install firefox
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install Firefox on OSX

  - bash: |
      brew update
      brew tap caskroom/cask
      brew cask install google-chrome
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install Chrome on OSX

  - bash: |
      sudo apt-get update --yes
      sudo apt-get install firefox --yes
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Install Firefox on Linux

  - bash: |
      npm install
      npm run build
    displayName: 'Generate javascript'
    continueOnError: false

  - bash: |
      ${{ parameters.robotPrefix }} inv test --outputdir $(outputdir) --xunit acceptance_tests.xml
    displayName: 'Running Acceptance Test'
    continueOnError: false

  - bash: |
      ${{ parameters.robotPrefix }} inv test --coverage --outputdir devnull
      inv cobertura --outputfile $(outputdir)/$(python_version)-$(os_name)-coverage.xml
    displayName: 'Running Coverage'
    condition: eq(variables['coverage'], 'true')
    continueOnError: false

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: $(outputdir)/acceptance_tests.xml
      testResultsTitle: Acceptance Tests for $(python_version) on $(os_name)
      testRunTitle: seleniumtestability-$(python_version)-$(os_name)-acceptance

  - task: PublishCodeCoverageResults@1
    condition: and(succeededOrFailed(), eq(variables['coverage'], 'true'))
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: $(outputdir)/$(python_version)-$(os_name)-coverage.xml
      failIfCoverageEmpty: false

# DOES NOT MOSTLY WORK IN WINDOWS FOR REASON OR THE OTHER WTF?
# running tests leaves process running and stuff in outputdir are still locked due to that ..
  - task: PublishBuildArtifacts@1
    condition: always()
    displayName: Publish Robot Framework logs and results
    inputs:
      PathtoPublish: $(outputdir)
      Parallelcopy: true
      Parallelcount: 8
      ArtifactType: container
      TargetPath: ""
      ArtifactName: ${{ parameters.name }}-$(python_version)-$(os_name)-logs
