trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - docs/*
jobs:
- template: azure/job_template.yml
  parameters:
    name: 'OSX'
    vmImage: 'macOS-10.14'
    coverage: 'false'
    timeout: 20
    chromedriver: 'latest'
    geckodriver: 'latest'
- template: azure/job_template.yml
  parameters:
    name: 'Windows'
    vmImage: 'VS2017-Win2016'
    robotPrefix: 'PATH=~/bin:${PATH}'
    coverage: 'false'
    timeout: 30
    chromedriver: '80.0.3987.106'
    geckodriver: 'v0.26.0'
- template: azure/job_template.yml
  parameters:
    name: 'Linux'
    vmImage: 'ubuntu-16.04'
    robotPrefix: 'PATH=~/bin:${PATH} xvfb-run --auto-servernum --server-args="-screen 1, 1600x900x24"'
    coverage: 'true'
    timeout: 20
    chromedriver: 'latest'
    geckodriver: 'latest'
- template: azure/artifacts.yml
  parameters:
    name: 'GenerateBuildArtifacts'

