name: SeleniumTestability tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8, 3.9, 3.10]
        browser: [chrome, firefox]
        nodejs: 16
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python $({ matrix.python })
      uses: actions/setup-python@v4
      with:
        python-version: "$({ matrix.python })"
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - uses: actions/setup-node@v3
      with:
        node-version: $({ matrix.nodejs })

    - name: Build javascript aassets
      run: |
        npm install
        npm run build

    - name: Running Acceptance Tests
      run: |
        inv test --skipci  --xunit acceptance_tests.xml
